/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import logica.Accidente;
import logica.Ambulancia;
import logica.Barrio;
import logica.Floyd1;

import logica.Grafo;
import logica.Pintar;
import logica.Profundidad;
import logica.SantaMarta;
import logica.logicaGrafo;

/**
 *
 * @author Jonathan Vizcaino
 */
public class MenuP extends javax.swing.JFrame {
    
    
    /**
     * Creates new form MenuP
     */
    Pintar ver = new Pintar();
    public SantaMarta conexBarrios = new SantaMarta();
        
    private  boolean isRunning;
    public MenuP() {
        
        initComponents();
        this.setLocationRelativeTo(this);
        setResizable(false);
        
        setImageLabel(jmapa, "src\\imagenes\\posibles\\mapasolo.png");
        
        isRunning = true;
        ejecucion();
    }
    boolean mostrarAristas = true;
    boolean mostrarVertices = true;
    private void ejecucion() {
        if (mostrarAristas || mostrarVertices) {
            Thread procesoThread = new Thread(() -> {
            while (isRunning) {
                pintar();
                
                try {
                    Thread.sleep(1000); 
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                }
            });
            procesoThread.start();
        }
    }

    
 
    private void pintar() {
        
        Graphics g = jPanel1.getGraphics();
        if (g != null) {
            if (mostrarVertices) {
                for (int i = 0; i < conexBarrios.barrios.orden(); i++) {
                int x = conexBarrios.corX.get(i);
                int y = conexBarrios.corY.get(i);
                Ambulancia ambu = conexBarrios.barrios.obtVertice(i).getTieneAmbu();
                if(ambu==null){
                    ver.pintarCirculo(g, x, y, "" + i); 
                }else{
                    ver.clickSobreNodo(g, x, y, ""+i, Color.red);    
                }}
                mostrarVertices = false;
            }
            
            if (mostrarAristas) {
                for (int i = 0; i < conexBarrios.barrios.orden(); i++) {
                    for (int j = 0; j < conexBarrios.barrios.orden(); j++) {
                        int x1 = conexBarrios.corX.get(i);
                        int y1 = conexBarrios.corY.get(i);

                        int x2 = conexBarrios.corX.get(j);
                        int y2 = conexBarrios.corY.get(j);
  
                        if (i != j && conexBarrios.barrios.obtArista(i, j) != conexBarrios.barrios.infinito() ) {
                            float tam = conexBarrios.barrios.obtArista(i, j );
                            ver.pintarLinea(g, x1, y1, x2, y2, tam);
                        }
                    }
                }
                mostrarAristas = false;
                mostrarVertices = true;
            }
        }
    }
    
    
    
    private void setImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        );    
        labelName.setIcon(icon);
        this.repaint();
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jmapa = new javax.swing.JLabel();
        generarArista = new javax.swing.JButton();
        aislarVertice = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualizar Grafo");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(141, 141, 141));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 102, 51)));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 522));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 522));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(null);

        jmapa.setMaximumSize(new java.awt.Dimension(37, 16));
        jmapa.setMinimumSize(new java.awt.Dimension(37, 16));
        jmapa.setName(""); // NOI18N
        jPanel1.add(jmapa);
        jmapa.setBounds(10, 10, 750, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 520);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        generarArista.setText("Generar aristas aleatorias");
        generarArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarAristaActionPerformed(evt);
            }
        });
        getContentPane().add(generarArista);
        generarArista.setBounds(30, 530, 190, 40);
        generarArista.getAccessibleContext().setAccessibleName("generarAris");

        aislarVertice.setText("Eliminar Todas las Aristas");
        aislarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aislarVerticeActionPerformed(evt);
            }
        });
        getContentPane().add(aislarVertice);
        aislarVertice.setBounds(260, 530, 180, 40);

        jButton1.setText("Aislar un vertice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 530, 130, 40);

        jButton2.setText("REINICIAR GRAFICO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 540, 150, 30);

        jButton3.setText("Situar Ambulancia/as");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 530, 150, 40);

        jButton4.setText("Reportar Accidente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 590, 190, 40);

        jButton5.setText("Recorrido ambulancia desde su barrio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 590, 260, 40);

        setSize(new java.awt.Dimension(1089, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyReleased

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        int x = evt.getX();
        int y = evt.getY();
        System.out.println("Clic en (" + x + ", " + y + ")");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void generarAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarAristaActionPerformed
        int numVer = conexBarrios.barrios.orden();
        int maximoVertices = (numVer-1)*numVer;

        String input = JOptionPane.showInputDialog(null, "Ingrese el número de aristas aleatorios (mayor que 0 y menor o igual a " + maximoVertices + "):");
        
        try {
    
            int numeroVertices = Integer.parseInt(input);

            if (numeroVertices > 0 && numeroVertices <= maximoVertices) {
                conexBarrios.eliminarTodasAristas();
                R_repaintEli();
                conexBarrios.geneArisGrafo(conexBarrios.barrios, numeroVertices);
               
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido en el rango especificado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.");
        }
        
  
    }//GEN-LAST:event_generarAristaActionPerformed
    public void R_repaintEli() {
        SwingUtilities.invokeLater(() -> {
            
            Graphics g = jPanel1.getGraphics();
            // Limpia el JPanel
            
            jPanel1.revalidate();
            jPanel1.repaint();

            
            mostrarAristas= true;
            mostrarVertices = true;
        });
    }

    public void R_repaintReiniciar() {
        SwingUtilities.invokeLater(() -> {
            
            Graphics g = jPanel1.getGraphics();
            //Limpia el JPanel
            //jPanel1.removeAll();
            jPanel1.revalidate();
            
            
            mostrarAristas = true;
            mostrarVertices = true;
        });
    }    
    
    
    private void aislarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aislarVerticeActionPerformed
        conexBarrios.eliminarTodasAristas();
        R_repaintEli();
    }//GEN-LAST:event_aislarVerticeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numVer = conexBarrios.barrios.orden();

        String input = JOptionPane.showInputDialog(null, "Ingrese la posicion del vertice que desea aislar\n(mayor igual que 0 y menor o igual a " + (numVer-1) + "):");
        
        try {
    
            int numeroVertices = Integer.parseInt(input);

            if (numeroVertices >= 0 &&  numeroVertices <= numVer) {
                conexBarrios.aislarBarrio(numeroVertices);
                R_repaintEli();

            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido en el rango especificado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        R_repaintEli();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String input = JOptionPane.showInputDialog("Ingrese la cantidad de ambulancias (deben ser mayor a 3 y menor que 6:");

        try {
            
            int cantidadAmbulancias = Integer.parseInt(input);

            
            if (cantidadAmbulancias > 3 && cantidadAmbulancias < 6) {
                ArrayList<Ambulancia> asituar = new ArrayList<>();
                for (int i = 0; i < cantidadAmbulancias; i++) {
                    String placa = JOptionPane.showInputDialog("Digite la placa de la Ambulancia número " + i+1 + ": ");
                    Ambulancia amb = new Ambulancia(placa);
                    asituar.add(amb);
                }
                conexBarrios.situar(asituar);
                R_repaintEli();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido de ambulancias.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido.");
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        Graphics g = jPanel1.getGraphics();
        int numVer = conexBarrios.barrios.orden();

        String input = JOptionPane.showInputDialog(null, "Ingrese la posicion del vertice donde hubo un accidente\n(mayor igual que 0 y menor o igual a " + (numVer-1) + "");
        try {
    
            int numeroVertices = Integer.parseInt(input);
            
            if (numeroVertices >= 0 &&  numeroVertices <= numVer) {
               
                int posIni = conexBarrios.enviarAmbulanciaMasCerca(numeroVertices);
                System.out.println(posIni);
                Floyd1 reco = new Floyd1(conexBarrios.barrios);
                    if (reco.f[posIni][numeroVertices] != conexBarrios.barrios.infinito()) {
                        reco.ruta(posIni, numeroVertices);
                        LinkedList<Integer> pos = reco.mrut;
                        pos.addFirst(posIni);
                        pos.addLast(numeroVertices);
                        for (int i = 1; i < pos.size(); i++) {
                            int x1 = conexBarrios.corX.get(pos.get(i-1));
                            int y1 = conexBarrios.corY.get(pos.get(i-1));

                            int x2 = conexBarrios.corX.get(pos.get(i));
                            int y2 = conexBarrios.corY.get(pos.get(i));

                            ver.pintarCamino(g, x1, y1, x2, y2, Color.yellow);
                        }
                        conexBarrios.barrios.obtVertice(numeroVertices).getAccidentesReportados().add(new Accidente("Tal/tal/tal", "Por tal tal tal.."));
                        conexBarrios.conAmbulancia.get(posIni).getAccidentesReportados().add(new Accidente("Tal/Tal/Tal", "Por tales y tales motivos..."));
                    }
                else{
                    JOptionPane.showMessageDialog(null, "El barrio esta aislado");     
                }
                    
                JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
                R_repaintEli();
                
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido en el rango especificado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public int buscar(String n){
        for (int i = 0; i < conexBarrios.barrios.orden(); i++) {
            if (n.equalsIgnoreCase(conexBarrios.barrios.obtVertice(i).getNombre())) {
                return i;
            }
        }
        return -1;
    }
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Graphics g = jPanel1.getGraphics();
        int numVer = conexBarrios.barrios.orden();

        String input = JOptionPane.showInputDialog(null, "Ingrese la posicion del vertice de donde quiere que la ambulancia\nHaga el recorrido (mayor a 0 menor a 32)");
        try {
    
            int numeroVertices = Integer.parseInt(input);
            
            if (numeroVertices >= 0 &&  numeroVertices <= numVer) {
                
                
                Profundidad prof = new Profundidad();
                prof.dfs(conexBarrios.barrios,numeroVertices);
                ArrayList<Integer> pos = new ArrayList<>();
                for (String visitado : prof.visitados) {
                    int posi = buscar(visitado);
                    pos.add(posi);
                }
                 
                
                for (int i = 1; i < pos.size(); i++) {
                    int x1 = conexBarrios.corX.get(pos.get(i-1));
                    int y1 = conexBarrios.corY.get(pos.get(i-1));

                    int x2 = conexBarrios.corX.get(pos.get(i));
                    int y2 = conexBarrios.corY.get(pos.get(i));

                    ver.pintarCamino(g, x1, y1, x2, y2, Color.yellow);
                }
                
                
                    
                 JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
                 R_repaintEli();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido en el rango especificado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.");
        }
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aislarVertice;
    private javax.swing.JButton generarArista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jmapa;
    // End of variables declaration//GEN-END:variables






}
